# Site settings
title: Buddy Reno | Web Developer | Nashville, TN
email: thebudman84@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here I say something inspirational.  No.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://buddylreno.github.io" # the base hostname & protocol for your site
twitter_username: buddylreno
github_username:  buddylreno

# Build settings
markdown: kramdown
# Using rouge http://sacha.me/articles/jekyll-rouge/
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: ["gulpfile.js", "node_modules", "README", "package.json", "Gemfile", "Gemfile.lock"]
