# Site settings
title: Buddy Reno // Web Developer // Spring Hill, TN
email: thebudman84@gmail.com
description: A web developer who loves technology and stuff.
baseurl: ""
url: http://buddylreno.github.io
twitter_username: buddylreno
github_username:  buddylreno
instagram_username: buddylreno
steam_username: buddylreno
permalink: /:title/
feed: ""
location: Nashville, TN

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
exclude: ["gulpfile.js", "node_modules", "README.md", "package.json", "Gemfile", "Gemfile.lock", ".editorconfig", ".gitignore"]
